<?php
    require_once("helpers/base_dados_helper.php");
    require_once("helpers/backoffice_helper.php");
    require_once("helpers/index_helper.php");
    require_once("helpers/contactos_helper.php");
    require_once("helpers/carousel_helper.php");
    require_once("helpers/portfolio_helper.php");
    require_once("helpers/privacidade_e_litigios_helper.php");
    require_once("helpers/servicos_helper.php");
?>